version: '3'
services:
  app:
    image: daan/request-mirror:latest
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis
    ports:
      - "6379:6379"
